apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed-service
  labels:
    service: udagram-api-feed-service
spec:
  selector:
    service: udagram-api-feed-service
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
